Solve most issues in MoquiStart.java
Only one bug remains:

Failed startup of context
oeje10w.WebAppContext@2f9a01c1{ROOT,/,b=file:///home/taher/Desktop/active/repositories/fork/moqui-framework/execwartmp/ROOT/webapp/,a=STOPPED,h=oeje10s.SessionHandler@2611b9a3{STOPPED}}{file:/home/taher/Desktop/active/repositories/fork/moqui-framework/moqui.war}
java.lang.IllegalArgumentException: URI is not hierarchical

So we need to find a solution for web.xml being inside the war file